//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GooglePhotoMap.GoogleMapPart {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint.WebControls;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System.Web.UI;
    using System;
    using System.Web.UI.WebControls;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Collections;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class GoogleMapPart {
        
        protected global::System.Web.UI.WebControls.ListBox waypoints;
        
        public static implicit operator global::System.Web.UI.TemplateControl(GoogleMapPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ListBox @__BuildControlwaypoints() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.waypoints = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "waypoints";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("name", "waypoints");
            @__ctrl.SelectionMode = System.Web.UI.WebControls.ListSelectionMode.Multiple;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::GooglePhotoMap.GoogleMapPart.GoogleMapPart @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
<div id='map_canvas' style='float:left;width:70%;height:400px'></div>
<div id=""control_panel"" style=""float:right;width:30%;text-align:left;padding-top:20px"">
    <div style=""margin:20px;border-width:2px;"">
        <b>Start:</b>
        <select id=""start"">
            <option value='Atlanta, GA'>Atlanta</input>
        </select>
        <br>
        <b>Waypoints:</b> <br>
        <i>(Ctrl-Click for multiple selection)</i> <br>
        "));
            global::System.Web.UI.WebControls.ListBox @__ctrl1;
            @__ctrl1 = this.@__BuildControlwaypoints();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        <br>
        <b>End:</b>
        <select id=""end"">
            <option value='Atlanta, GA'>Atlanta</input>
        </select>
        <br>
            <input type=""submit"" onclick=""calcRoute(); return false;"">
    </div>
    <div id=""directions_panel"" style=""margin:20px;background-color:#FFEE77;""></div>
</div>"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
